### ISSUE TITLE
Workflow should account for niceness of different tasks

### ISSUE THREAD

**Issue by wbazant** [Nax/longflow-manifesto#10]
I am using Unix's niceness of processes (https://en.wikipedia.org/wiki/Nice_(Unix)) and a metaphor of a developer as a process scheduler that shares a central processing unit (her time and brains) between the processes (tasks).

I like the description of a workflow when confined to within a task. I would like it to account for the niceness of tasks varying as you work on them - it can happen that while thinking about a task we realise that it is much more urgent than originally thought, or after preliminary work and achieving some results we realise that further work on the task won't add much value.

As a second and similar point, learning something new that a developer feels like learning should be probably modelled as forking into a child process, with an appropriate nice value.

**Comment by Nax** [comment]
https://github.com/Nax/longflow-manifesto/issues/7 is similar, but based on cost rather than arbitrary niceness.

I like your idea of abstracting away the priority (or niceness, which is just negative priority). Each implementation can then map such niceness to a more concrete value if they want to (cost or whatever).

About the second point, I am not sure the forking metaphor is optimal. I see where you're coming from: learning something is a task too, but I don't think there must be a parent-child relationship between the two.

I think a better model would be a scheduler, which (hopefully) should prioritise some threads but never starve any of them. Often in scrum projets, maintenance tasks like refactoring are starved by the constant flow of high priority tasks.
