### ISSUE TITLE
Technical marvel VS MVP

### ISSUE THREAD

**Issue by Sashkan** [Nax/longflow-manifesto#12]
After a few years wandering around on both sides, either as a commercial or as a developer, I wanted to add my 2 cents about what's in this manifesto. I think that it is 100% accurate when it comes to the current state of programming languages: we all crave for everlasting learning, self-improvement and code optimization. 

But the thing is, we have to make choices, that can only be defined by our available resources, and when it comes to code, there are but two of them: time, and money.

Now, if your plan is to build a technical marvel, some kind of next-level architecture/application, then this manifesto is a text to live by, espeicailly if you have free time (Like, let's say, you're still a student in a wonderful tuition-free, 27/7 open school...). As a developer, the only thing we'll ever produce is technical legacy, which means we'll have to improve, learn, enhance, whatever you want to keep on building a great application.

But when it comes to company product, you have to find a balance between this idea of technical masterpiece and the limited time and money you have. The very idea of building a business is going through very few steps, building a basic product/demo, to get enough money to start building/hiring devs to build your real application, and THIS is where scrum comes in handy: the sole purpose of scrum method is to allow some kind of transparency, to set limits about the 3 real questions when it comes to coding a MVP:
- What do we REALLY need ?
- How can we produce it ?
- How long will it take ?
IMHO, Scrum was created to make product development easier, and slowly turned into a way to monitor developers efficiency.

**Comment by Nax** [comment]
> But the thing is, we have to make choices, that can only be defined by our available resources, and when it comes to code, there are but two of them: time, and money.

Not from the POV of the business. Time is never a limiting factor, as proven by the many companies which outlived their founder(s).

> But when it comes to company product, you have to find a balance between this idea of technical masterpiece and the limited time and money you have.

Again, as long as we're speaking about surviving as a company, time is not a factor. If you need product A to be ready in less than 6 month, but you'll be fine if it was not if you had an extra $300k, then the problem was never about time, only about money.

> The very idea of building a business is going through very few steps, building a basic product/demo, to get enough money to start building/hiring devs to build your real application [...]

As you just said, "to get enough money". Just like I said before, it's all about money.

Also, I strongly disagree about this being "The very idea of building a business". If it works for you, then more power to you, but I think the goal of a product-oriented business is, by definition, to build a (good) product. Everything else is an implementation detail and should be managed in a case-by-case basis. Especially, building a MVP may or may not be relevant depending on what you're doing. It may not even be possible to prototype a MVP before getting funds if you're working on something moderately complex. Same goes for VC fundings, it may or may not be relevant, and may be substituted by personal funds, or crowdfunding, or a bank, whatever.

Also, since we're talking about money : technical debt is debt. Period. Bug are not going to be fixed for free, and technical debt makes adding features exponentially slower and/or buggy. That's going to cost much, much more than if problems were fixed on the fly.

> [...] and THIS is where scrum comes in handy: the sole purpose of scrum method is to allow some kind of transparency, to set limits about the 3 real questions when it comes to coding a MVP [...]

I disagree here too. Early product development is where scrum is the most inefficient and the most damaging.

I understand the reasoning : scrum allows us to focus on what matters and so, reduce development cost & time.

But it's based on a flawed premise : that you can, in fact, reduce development time. The truth is, and you know it, since you're a developer yourself; you can't. I'm sorry, but you can't. It's not gonna happen.

Sure, you can hire better devs, or more of them (but don't do that if you're already late, it's only getting worse if you do), but then? Does scrum makes me implement a function faster? No. Does longflow makes me implement the same function faster? Neither. That's why it's focused on two things:

 * Reducing time spent elsewhere (during meetings, for example)
 * Create good code hygiene and a nice environment, which increase productivity on the long term, by automating tasks, making the code cleaner and so easier to understand and edit, whatever.

For what happens when you try to force devs to produce more features in less time, I suggest you read *The Mythical Man-Month* by Fred Brooks. It contains terrible stories about projects where policies designed to reduce development time made them explode instead.

**Comment by Sashkan** [comment]
I think you misunderstood my message: it was not about giving my point of view, but rather explaining what saddens me in this "agile" architecture. If I had to pick/build a workflow, I'd never ever go for something scrum-related. 

I personally think that, as you said, the main task should be to focus on the product, no matter how long it might take (in fact, it might never end).

I'll make sure to read the book you mentionned.

An interesting alternative to this "Agile" thing can be the Squad Process, initialized by Spotify.
You might also take a look at [this article](https://www.pandastrike.com/posts/20150304-agile), which was written in early '15 but still points out most of the flaws in this SCRUM process.

TBH, you can read all of the SCRUM guides you'll ever find, and still end up with a shitty product. Maybe it's because of the 42-process spirit, but I prefer to read [a shitload of tutorials](https://github.com/sindresorhus/awesome) , then plan every step of the process, consistently focusing on clean, efficient code, and then start coding. Maybe it's not the most time-efficient method, and maybe it will take me way more time to produce my feature, but who cares if the product is perfect ?
