### ISSUE TITLE
a lot of personal frustration

### ISSUE THREAD

**Issue by tspycher** [Nax/longflow-manifesto#5]
This manifesto proves that a lot is not working the way it should at your employer. Therefor it is worth to write it down to sort out your feelings and think about what should change. Maybe you have to change your views on business as well to make yours and the life of your supervisors easier.

From a management and technical perspective this manifesto is ~~just bullshit~~ really useful at the moment. Reflect, Learn, Change and move forward. Good Luck Buddy! We all went and are going trough this feelings. Its a f*** part of our Business.

**Comment by Nax** [comment]
And it is bullshit because ...?

**Comment by tspycher** [comment]
...because the content is solely driven by personal frustration. And does way not reflect the real world and the business perspective.

**Comment by Nax** [comment]
Assuming this is the case, how would it be a problem?

**Comment by tspycher** [comment]
As mentioned; its important to deal with frustration! You'r trying to find a way, which is good!, but selling your frustration as a "new way of software development" is not really that productive. Every software developer knows your feelings very well and as i'm doing right now, we'r here to help. Even if it means to say "stop, don't do that buddy". :)

**Comment by crsrusl** [comment]
@tspycher very negative comments here... Let's try and be constructive rather than slinging mud.

**Comment by ido50** [comment]
It's personal frustration that brings out the best ideas out of people. Anyway, I don't think this manifesto is bullshit, nor did I feel like it came from "a lot of personal frustration". It touches on a lot of real problems with today's development methodologies. If the solution it suggests is a good one, that's a different subject.

**Comment by kube** [comment]
@tspycher We can also see your reaction as the reaction of somebody who submitted to the software industry standards, and who is a little embittered.

Maybe it's just idealism, maybe this method won't be able to compete Scrum method in terms of rentability, but it's a good thing to see people trying to think again about the condition of programmers in the software industry, and propose new methods.

I see this like a method for "Haute couture" programming (@Nax won't like this word).
Maybe it's more dedicated to craftsmen who really want to produce quality, and maybe it will change how this industry see things.

Things do not have to stay how they are forever, maybe it's time for a change.

**Comment by FagnerMartinsBrack** [comment]
Agree with @crsrusl, "this manifesto is just bullshit" doesn't help anyone, really.

**Comment by EvidentlyCube** [comment]
I agree that flat out calling it "bullshit" is not productive so instead let me address one thing.

> Estimates are to be avoided at all cost. They create needless pressure, competition, and participate in a toxic witch-hunt of who is the less productive.

If estimations create pressure, competition and witch-hunt then it's not the estimations that are the problem, it's the whole company. If it's managed by people who don't understand that productivity of a programmer (or a designer or many other types of creative jobs) can't be measured with simple numbers then maybe it's time to update your CV.

Estimations are never meant to be surgeon-like precise. You should usually aim for an order-of-magnitude precision. Tasks which take an hour, half a day, a day, two days, a week, two weeks, a month. No one can guess that refactoring the API module in your app will take 15 days, 4 hours and 3 minutes. But you can reasonably say it'll be at the order of magnitude of a month.

And then when a client comes and asks when the new version is going to be rolled out...
Or when management wants to decide which features' ROI is not negative...
Or when it needs to be decided when a new person has to be hired...
Or someone has to be laid off...

...They can look at meaningful numbers.

**Anecdotal evidence time!**

In my personal experience the friction created by estimations comes from these things:

 - Inexperienced devs suffering from [Dunning-Kruger Effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect) or people who overestimate their own skills and do super-low estimations (or just anyone deflating the estimations for no good reason)
 - Young teams which don't yet know how much buffer they need to add to the estimations
 - Not including the time to test and deploy the changes in the estimations (which should not be done by the programmer if they are not the one doing those things btw.)
 - Management trying to do a witch-hunt for least productive people and not understanding that not everything can be quantified into numbers
 - A pressure to give the lowest bids possible
 - New tasks added mid-sprint or just in the middle of doing another task

And some ways to overcome them:

 - Educate the management, talk to them like to real people, not someone you are forced to waste your time on. Surprisingly lot can be achieved by being polite, understanding and clear. Though there are some people you just can't get to.
 - Do a variant of planning poker or something so that everyone in the team can voice their opinion about estimation
 - Track your own estimations - if usually you need more time to do things you estimated then add more time next time you estimate
 - Don't get yourself pressured into doing tasks using someone else's estimations - keep a paper trail that you've complained about it and when they later hold it against you you can show them they're in the wrong

**Comment by tspycher** [comment]
I'm sorry for the bullshit statement. It might be a bit too harsh.
There are many statements i completely disagree in this manifesto because they are so harmful for any developer, the company itself and the project the developer is working on. But i do understand the motivation to write them down and finding a way to deal with it.

**Comment by tspycher** [comment]
And finally it would support the stereotype programmer. Unwilling to communicate, unable to give a rough estimation of pending task. Is not flexible enough to support the Business with with simple solutions and usually is "overengineering" simple tasks.

**Comment by FagnerMartinsBrack** [comment]
> And finally it would support the stereotype programmer. Unwilling to communicate, unable to give a rough estimation of pending task. Is not flexible enough to support the Business with with simple solutions and usually is "overengineering" simple tasks.

A.K.A, [the angry dev](https://hackernoon.com/the-angry-programmer-52a93bfcbc3c). It's just a phase everyone goes through as software developers. Some overcome it, some don't.
